### PR TITLE
Namespaces with hyphen are inline in drawer

### LINKED ISSUE #162: Fix bug in display of namespaces with hyphens
## Expected Behavior

Display hyphenated namespaces in a single-line format (like unhyphenated namespaces). 

## Current Behavior

Namespaces with hyphens (e.g. `sensu-system`) are displayed using the old two-line layout - a vestige from the Sensu alpha/beta releases when we were using orgs & environments instead of namespaces. This is probably somehow related to the backwards compat plan we had to map any pre-existing org/environment configs to hyphenated namespaces. 

Example: 

image

## Possible Solution

Display hyphenated namespaces in a single-line format (like unhyphenated namespaces). 

## Steps to Reproduce

Create a hyphenated namespace. :) 

## Context

Using namespaces? 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.10.2
* Installation method (packages, binaries, docker etc.): 5.10.2
* Operating System and version (e.g. Ubuntu 14.04): 5.10.2
* Browser used: Chrome (on Chrome OS)

### PR DESCRIPTION
**Pull request by dabria**
## What is this change?
Closes #162 
Changes the namespace selector in the drawer to show namespace in one line, just like the topbar.

Screen Shot 2019-07-10 at 9 47 37 PM

## Why is this change necessary?
It was requested.

### CODE REVIEW

**Comment by calebhailey** [comment]
Thanks! Can we also make the full string the same color? Looks like the text before the hyphen is still getting styled differently.

**Comment by dabria** [comment]
@calebhailey Would you like the namespace in the topbar (top right) to look the same in that case?

**Comment by dabria** [comment]
Screen Shot 2019-07-11 at 10 38 04 AM
Screen Shot 2019-07-11 at 10 38 11 AM

**Comment by calebhailey** [comment]
This looks good! 

> @calebhailey Would you like the namespace in the topbar (top right) to look the same in that case?

Yes, that would be great. Thanks! 🎉

**Comment by calebhailey** [comment]
🎉 

Thanks again, @dabria! 🙌

**Pull request merged**
